name: llm_telegram_bot-dev

services:
  bot:
    build:
      context: .
    image:
      llm_telegram_bot-bot:${COMMIT_SHA:-default}
    env_file:
      - .env.dev
    restart: unless-stopped
    volumes:
      - ./src:/srv/src


  mongo:
    image: mongo:4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo_data_dev:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
