name: llm_telegram_bot-local

services:
  bot:
    build:
      context: .
      target: runtime
    image:
      llm_telegram_bot-bot
    env_file:
      - .env.dev
    volumes:
      - ./src:/srv/src
    restart: always

  mongo:
    image: mongo:4
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo_data_local:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
